source 'https://rubygems.org'
# gem 'github-pages'
gem 'jekyll'
gem 'jekyll-mentions'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jemoji'
gem 'kramdown'
gem 'liquid'
gem 'maruku'
gem 'rdiscount'
gem 'redcarpet'
gem 'RedCloth'